{"name": "Проверка возвращении ошибки при создании курьера с одинаковым логином", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\n  \n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.", "trace": "self = <tests.test_create_courier.TestCreateCourier object at 0x00000187DED5EF10>\n\n    @allure.title('Проверка возвращении ошибки при создании курьера с одинаковым логином')\n    def test_post_create_2_same_login_courier_failed(self):\n        courier = Courier()\n        courier.create_new_courier(Data.courier_same_login_password_1)\n        create_courier_same_login = courier.create_new_courier(Data.courier_same_login_password_2)\n        assert create_courier_same_login.status_code == 409\n>       assert create_courier_same_login.json()[\"message\"] == Data.create_courier_same_login_message\nE       AssertionError: assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\nE         \nE         - Этот логин уже используется\nE         + Этот логин уже используется. Попробуйте другой.\n\ntests\\test_create_courier.py:32: AssertionError"}, "start": 1717232905373, "stop": 1717232905997, "uuid": "d301cba1-8835-4b19-877d-56e36c08f499", "historyId": "3769cd6c8c1543cd45fed9a6c3676a5e", "testCaseId": "3769cd6c8c1543cd45fed9a6c3676a5e", "fullName": "tests.test_create_courier.TestCreateCourier#test_post_create_2_same_login_courier_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "WIN-A5H5V66RP32"}, {"name": "thread", "value": "14664-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}