{"name": "Проверка возвращении ошибки при создании курьера с одинаковым логином", "status": "passed", "start": 1717005290259, "stop": 1717005290788, "uuid": "1508bdc6-051d-468f-9b13-8260f9fc1395", "historyId": "3769cd6c8c1543cd45fed9a6c3676a5e", "testCaseId": "3769cd6c8c1543cd45fed9a6c3676a5e", "fullName": "tests.test_create_courier.TestCreateCourier#test_post_create_2_same_login_courier_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "WIN-A5H5V66RP32"}, {"name": "thread", "value": "24876-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}