{"name": "Проверка возвращении ошибки при авторизации несуществующего пользователем", "status": "passed", "start": 1717232911187, "stop": 1717232911495, "uuid": "c1d1f3e6-fee4-4eea-b4a8-667fbcbaf051", "historyId": "be613a4698c9ac275609301b15857e5e", "testCaseId": "be613a4698c9ac275609301b15857e5e", "fullName": "tests.test_login_courier.TestLoginCourier#test_post_login_courier_no_exist_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "WIN-A5H5V66RP32"}, {"name": "thread", "value": "14664-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}