{"name": "Проверка возвращении ошибки при создание одинаковых курьеров ", "status": "passed", "start": 1717005282103, "stop": 1717005290257, "uuid": "88fdb33d-ee05-4288-8925-06b26e386bac", "historyId": "63b78487c2161f139dd3a7b6569650a3", "testCaseId": "63b78487c2161f139dd3a7b6569650a3", "fullName": "tests.test_create_courier.TestCreateCourier#test_post_create_2_same_courier_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "WIN-A5H5V66RP32"}, {"name": "thread", "value": "24876-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}