{"name": "Проверка возвращении ошибки при создание одинаковых курьеров ", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\n  \n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.", "trace": "self = <tests.test_create_courier.TestCreateCourier object at 0x00000187DED5EA90>\n\n    @allure.title('Проверка возвращении ошибки при создание одинаковых курьеров ')\n    def test_post_create_2_same_courier_failed(self):\n        courier = Courier()\n        create_courier_1 = courier.create_new_courier(Data.courier_login_password)\n        create_courier_2 = courier.create_new_courier(Data.courier_login_password)\n        response = create_courier_2\n        assert response.status_code == 409\n>       assert response.json()[\"message\"] == Data.create_courier_same_login_message\nE       AssertionError: assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\nE         \nE         - Этот логин уже используется\nE         + Этот логин уже используется. Попробуйте другой.\n\ntests\\test_create_courier.py:24: AssertionError"}, "start": 1717232904711, "stop": 1717232905363, "uuid": "d9280f86-4f6c-4b35-8f0d-cc0e8d9212d5", "historyId": "63b78487c2161f139dd3a7b6569650a3", "testCaseId": "63b78487c2161f139dd3a7b6569650a3", "fullName": "tests.test_create_courier.TestCreateCourier#test_post_create_2_same_courier_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "WIN-A5H5V66RP32"}, {"name": "thread", "value": "14664-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}